services:
  # --- FastAPI App ---
  api:
    build: .
    container_name: fastapi-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://task_user:123456@postgres:5432/task_db
    depends_on:
      - postgres
    volumes:
      - .:/app

  # --- Postgres Database ---
  postgres:
    image: postgres:16
    container_name: taskmanager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

volumes:
  postgres_data_v2:
